### PR TITLE
Improve transfer speed  && migrate to serial2

### LINKED ISSUE #95: Maximum transmission rate is severely limited
When transferring large amounts of data continuously, the transfer rate of serial-monitor-rust is much slower than other serial port software (e.g. serialplot). Comparisons as following:
image
image
The serial-monitor-rust receives a line every 0.025s, indicating the transfer rate of 25 sps. But the serialplot achieves  359 sps.

### PR DESCRIPTION
**Pull request by L-Trump**
Reopen from #96 , with merges from #94 .

Fix #95 . Retrieving the latest available device in each data transfer loop significantly slows down the transfer rate. This pr uses the BrokenPipe IO error to determine the disconnection externally.

Migrate to serial2 crate as proposed in #94 . Already tested on linux x64.

### CODE REVIEW

**Comment by L-Trump** [comment]
Please DO NOT merge this pr in current state!! It seems that serial2 read broken datas with high transfer rate. I would confirm it in this weekend. Thanks!

**Comment by L-Trump** [comment]
Test on Arch Linux x64. I have no idea about why the serial2 cannot work correctly in high data rate, but it does occur. So I withdraw the migration to serial2. Acutally, the performance improvement of serial2 mainly lies in the simultaneous high-speed reading and writing on Windows, which may not a common perpose for this project, as we only send command manually.

**Comment by hacknus** [comment]
Sorry it took me so long to look over this.
Thanks a lot for the contribution! I noticed though that this now requires features that are not stable yet. 

```
use of unstable library feature 'vec_into_raw_parts': new API
```

can we replace this with only stable code?

**Comment by L-Trump** [comment]
Oh sorry I didn't make it clear what changes I made. For this pr, corresponding to the serial2_merge branch of my fork, I only make changes for transfer speed improvement. Thus there's no problem to just merge this pr. I've changed the project a lot in the main branch of my fork. These changes are only for my own needs (add some features similar to serialplot, I need a data collector). Of course, I can sync some features over if you really need them.

**Comment by L-Trump** [comment]
In addition, since the current code completely clones the entire DataContainer each time data is collected, high-speed data transfer is likewise not possible without limiting the data length, and there may be a risk of memory overflow.

**Comment by hacknus** [comment]
Oh yes, sure! Sorry I pulled the wrong branch. Thanks!

**Pull request merged**
