### PR TITLE
Sentence highlightment

### PR DESCRIPTION
**Pull request by simon0356**
Hello there !

Even if I'm I huge fan of minicom I was looking for a serial monitor that allow me to perform sentence highlightment.
I find you plots feature interesting even if i haven't use it so far but i'm sure I will.
I'm still not a rust Guru and this is still work in progress but i wanted to share it with you and get your opinions on it.
I have concern on how much the sentence search using regex will load the CPU. 
For sure it will be possible to save previously found sentence and only doing the search process on new lines.
Also I was wondering if 
- it is possible in egui to not perform a full reload of the "console_scroll_area" to preserve CPU
- to reduce FPS when no new frames was available and to force a repaint_request on RX/TX messages
Here is some capture i have done : 
serial_monitor_2
serial_monitor
ps : For the screenshot I got no "publicly" shareable UART trace so i force the content with same content as your screenshot, that why there is no graph on the screen

Thanks
Simon

### CODE REVIEW

**Comment by hacknus** [comment]
Cool, thanks for the input and this idea - looks really cool, I'll look into the code changes! As for your questions:

> - it is possible in egui to not perform a full reload of the "console_scroll_area" to preserve CPU. 

I don't think so. It reloads the full GUI also when you move your cursor as far as I know...
> - to reduce FPS when no new frames was available and to force a repaint_request on RX/TX messages. 

This would be worth looking into! Could be implemented with a sync-channel that always sends a value when a refresh is requested. We would then replace this line in `gui.rs`

```rust 
       std::thread::sleep(Duration::from_millis((1000.0 / MAX_FPS) as u64));
```
with something like this:
```rust 
       if let Ok(_) = request_refresh_rx.recv_timeout(Duration::MAX) {
        // just wait until a refresh is requested
       }
```
could also use `request_refresh_rx.recv()` without a specified timeout...

**Comment by simon0356** [comment]
I have rebased your main since you did the optimization for the refresh. Thanks !

**Comment by hacknus** [comment]
Thanks a lot for the work, this looks great! However, I think the two "tabs" for plot and highlighting are not super obvious. I don't have a clear picture of what would improve it, maybe leaving the plot settings as default and adding a "Advanced Settings" button which opens a settings window with the highlighting settings?

or having the "Plot settings" and the "Highlighting Settings" as collapsible options if that works with egui?

Because right now they are just two buttons that switch between modes, but it is not clear what they do, before one presses the buttons.

What do you think?

**Comment by simon0356** [comment]
I agree that i was myself not convinced by my UI proposal, I will try to  work on it as soon as possible.

Thanks for you feedback !

**Comment by simon0356** [comment]
I have created collpasing menu for Highlighting, Plot and Export ( i also create function for each of this settings) with a vertical scroll .
serial_monitor
serial_monitor_2

**Comment by hacknus** [comment]
Cool, I think this will work nicely with my other PR where the Debug Info will also be a collapsible menu item: #106 

Please supply a new entry into the changelog. I'll merge it, once I'm able to test it with hardware!

**Comment by simon0356** [comment]
I have edit the changelog.
I think it could be nice to run an indenter in gui.rs, but I will let you look to.

**Comment by hacknus** [comment]
Sorry for the delay, thanks a lot for the contribution!!

**Pull request merged**
